### PR TITLE
New North American indigenous languages.

### PR DESCRIPTION
**Pull request by snomos**
Added a number of North American languages being worked on or being planned. Also added the language 'mis' for the country XX, to be able to demonstrate spellers and features for a neutral, non-existing language in a non-existing country in cases where existing languages would not really do the technology justice.

### CODE REVIEW

**Comment by aarppe** [comment]
These are the North-American languages in the language families which we are currently working at the Alberta Language Technology Lab (ALTLab) in the Department of Linguistics, University of Alberta, together with collaborators in Canada and the U.S., in creating proofing tools for, in the first instance spell-checkers.

**Comment by hatapitk** [comment]
Thanks for this! I'm a bit surprised though that these mappings are needed at all. For example alq-CA is not a known language in LibreOffice and thus the mapping from "alq" to "alq" in LibreOffice should work automatically. Could you briefly explain how adding these mappings changes the behavior of the program? There might be a bug out there that I could fix, if not then I will of course merge this patch.

**Comment by hatapitk** [comment]
This and #5 might in fact be related.

**Comment by aarppe** [comment]
Terve Harri,

On 2016-05-30 1:32 PM, Harri Pitkänen wrote:
> Thanks for this! I'm a bit surprised though that these mappings are needed at
> all. For example alq-CA is not a known language in LibreOffice and thus the
> mapping from "alq" to "alq" in LibreOffice should work automatically. Could you
> briefly explain how adding these mappings changes the behavior of the program?
> There might be a bug out there that I could fix, if not then I will of course
> merge this patch.

Sjur would know more about this than me.

I can't remember the exact details right now, but my understanding has been that 
without these mappings in Voikko, the spell-checking files (LibreOffice .oxt 
extensions) are not appropriately recognized with LibreOffice. So, even typing 
in the ISO code in the language selection, nothing happens, or that the language 
has a spell-checker is not evident as available in the Preferences.

Of the languages that we work with, only crk (Plains Cree) is a language 
"officially" recognized within LibreOffice - for the others we'd need to use the 
ISO code. Apparently then, there's some sort of malfunction in LibreOffice which 
requires that one goes to Preferences and opens Writing Aids subsection, and 
then just presses ok without doing anything to get a ISO-based speller to 
activate/work.

	-Antti
-- 
======================================================================
Antti Arppe - Ph.D (General Linguistics), M.Sc. (Engineering)
Assistant Professor of Quantitative Linguistics
Department of Linguistics, University of Alberta
E-mail: arppe@ualberta.ca, antti.arppe@iki.fi
WWW: http://www.ualberta.ca/~arppe
Maanahtu ina reedûti ihza ummânuuti ihannaq - dulum ugulak úmun ingul
----------------------------------------------------------------------

**Comment by aarppe** [comment]
Hello all,

So last evening I checked what happens in the case of Northern East Cree (ISO: 
crl) within LibreOffice.

If in the Language Selection box I try to type in 'crl-CA', I do not seem to get 
the speller that I've compiled for crl to work within LO (i.e. underline 
misspelled words and provide suggestions), but if I enter only the ISO language 
code without a country code, i.e. 'crl', then it certainly works (after going 
through the piruette of open Language Settings in Preferences and okaying things 
without any changes).

(As an important aside, this detour through Language Settings in Preferences 
that seems to be necessary a part of the installation process is something we'd 
like to get rid off, as it will confuse all too many Indigenous language 
end-users without a strong technical background, but how to best go about that 
is not obvious to me. Is it a LO-internal behavior in dealing with language 
tools only accessible ISO codes, where we have to file in a bug report with the 
LO folks, or a result of whatever language code information Voikko passes on to 
LO, potentially meaning it should be resolved within Voikko?).

Anyhow, in the case of Plains Cree I can (and need to) use the country code as 
well, i.e. crk-CA, to get the speller to work (using 'crk' results in no 
proofing activity). Any ideas as to why I get this apparent discrepancy in what 
type of code to use for proofing language selection.

	-Antti

On 2016-05-30 2:00 PM, Antti Arppe wrote:
> Terve Harri,
>
> On 2016-05-30 1:32 PM, Harri Pitkänen wrote:
>> Thanks for this! I'm a bit surprised though that these mappings are needed at
>> all. For example alq-CA is not a known language in LibreOffice and thus the
>> mapping from "alq" to "alq" in LibreOffice should work automatically. Could you
>> briefly explain how adding these mappings changes the behavior of the program?
>> There might be a bug out there that I could fix, if not then I will of course
>> merge this patch.
>
> Sjur would know more about this than me.
>
> I can't remember the exact details right now, but my understanding has been that
> without these mappings in Voikko, the spell-checking files (LibreOffice .oxt
> extensions) are not appropriately recognized with LibreOffice. So, even typing
> in the ISO code in the language selection, nothing happens, or that the language
> has a spell-checker is not evident as available in the Preferences.
>
> Of the languages that we work with, only crk (Plains Cree) is a language
> "officially" recognized within LibreOffice - for the others we'd need to use the
> ISO code. Apparently then, there's some sort of malfunction in LibreOffice which
> requires that one goes to Preferences and opens Writing Aids subsection, and
> then just presses ok without doing anything to get a ISO-based speller to
> activate/work.
>
>      -Antti

-- 
======================================================================
Antti Arppe - Ph.D (General Linguistics), M.Sc. (Engineering)
Assistant Professor of Quantitative Linguistics
Department of Linguistics, University of Alberta
E-mail: arppe@ualberta.ca, antti.arppe@iki.fi
WWW: http://www.ualberta.ca/~arppe
Maanahtu ina reedûti ihza ummânuuti ihannaq - dulum ugulak úmun ingul
----------------------------------------------------------------------

**Comment by hatapitk** [comment]
> Is it a LO-internal behavior in dealing with language tools only accessible ISO codes, where we have to file in a bug report with the LO folks, or a result of whatever language code information Voikko passes on to LO, potentially meaning it should be resolved within Voikko?

We have observed the same issue with the internal Hunspell spell checker in LibreOffice so it should be filed as a bug there. In fact I thought it was already reported last year but could not find the report anymore. I will file the bug tomorrow.

**Comment by aarppe** [comment]
In addition, we observed today that this behavior appeared to be in reverse in 
the Windows version of LO, where at least in the case of Northern East Cree one 
needed to use the code: crl-CA to get the spell-checker to function, instead of 
the code: crl, as was the case in MacOS (El Capitan).

**Comment by hatapitk** [comment]
The LibreOffice bug has now been reported here: https://bugs.documentfoundation.org/show_bug.cgi?id=100194

Looking at the code of libreoffice-voikko I can see that in <code>VoikkoHandlePool.__containsLocale</code> we may be too strict when comparing <code>localeToFind</code> against the list of supported locales. If for example we get a locale that has both language and country set and our dictionary only has language it should be accepted but now it is rejected. I will try fixing this next week.

**Comment by hatapitk** [comment]
This was a bit more complicated than I assumed. Apparently LibreOffice internally handles the list of supported spelling locales rather statically. That list is matched exactly to text language without considering whether the text could be covered by a speller with a less specific tag. Thus we need to explicitly advertise the support for each language AND language-country pair we want to support.

I merged the pull request and also added a mechanism in c6e38f12be8b03c4ae556d27159e14ebf8b9d0c3 to specify that certain languages should also be supported without country. (Why not do that automatically? Because then we our "fi" speller would be advertised to support both "fi" and "fi-FI" which is technically correct but works badly with the way how legacy locales work in LibreOffice: we would get both "fi" and "Finnish" in the supported spelling languages list and we only want to see "Finnish".)

**Comment by aarppe** [comment]
So, this allows for spellers for languages associated with only a single country code, and which are identified only with the ISO codes, to be accessible without categorically needing to specify the country code?

Therefore, Northern East Cree, spoken and written only in Canada, can be referred to by crl or crl-CA, but Odawa, used on both sides of the border, needs to be referred to by either otw-CA or otw-US, and using otw does not automatically pick up a speller for otw-CA or otw-US, if only one of these have been installed on one's computer?

**Comment by hatapitk** [comment]
> but Odawa, used on both sides of the border, needs to be referred to by either otw-CA or otw-US, and using otw does not automatically pick up a speller for otw-CA or otw-US, if only one of these have been installed on one's computer?

That's right. The problem is that if both otw-CA and otw-US are installed which one should be picked if otw is requested? I think that randomly selecting one could create confusion. I don't know about this particular language but thinking about Swedish if I would have both sv-SE and sv-FI installed and then requested speller for "sv" I would hope to get "sv-SE". Solving this would require some work in libvoikko such as ability to specify alternate tags for a single dictionary.

**Comment by aarppe** [comment]
In the case of otw (Odawa), it's spoken mostly on the Canadian side of the Great Lakes, but historically in Michigan as well. As far as I know, there wouldn't be major differences, other than perhaps in proper name recognition, though we don't exactly know yet if there'd be genuine dialectal differences as well.

I agree that it should be user who determines which one of the two they want to use, and they'd need to do that explicitly. So if you are forced to specify the languages as otw-CA or otw-US, especially when both files are installed, that makes the choice explicit for the user. Of course, it you would have just one of the two installed, then it might possibly make sense that you could invoke that one with just the simple otw language code. But maybe even then the requirement of being exposed to the country code alongside the language one would make one aware of that there might be other variants (whether it matters if there are any genuine differences between the two country-code variants is another thing).

**Pull request merged**
